### ISSUE TITLE
Relationship with jade-runtime

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade-attrs#2]
AFAICS this module does the same thing as (and a little more than) jade.attrs. So, what's the relationship between these two? Is this module meant to replace the implementation in jade-runtime?

**Comment by ForbesLindesay** [comment]
`runtime.attrs` does the job of taking an object that maps attribute keys to values and generating the html for those attributes.  This is used by the `&attributes` syntax.  `jade-attrs` deals with generating code to produce attributes objects (e.g. to be given to mixins) and producing html directly.  They're actually fairly separate jobs.

To sumarise

**jade-attrs**
Array from jade parser -> JavaScript -> HTML
Array from jade parser -> JavaScript -> Object mapping keys to values

**runtime.attrs**
Object mapping keys to values -> HTML

**Comment by TimothyGu** [comment]
Alright, makes sense.
